
language: csharp
mono: none
dotnet: 3.0
before_script:
    - dotnet restore ./EventFlowSample/EventFlowSample.sln
    - dotnet build ./EventFlowSample/EventFlowSample.sln
script:    
    - dotnet test 
