dist: xenial
language: csharp
mono: none
dotnet: 6.0
services:
  - postgresql
addons:
  apt:
    packages:
    - rabbitmq-server
before_script:
    - dotnet restore ./EventFlowSample/EventFlowSample.sln
    - dotnet build ./EventFlowSample/EventFlowSample.sln
script:    
    - dotnet test ./EventFlowSample/GettingStartedTest/GettingStartedTest.csproj
