
language: csharp
mono: none
dotnet: 3.0
services:
  - rabbitmq
  - postgresql
before_script:
    - dotnet restore ./EventFlowSample/EventFlowSample.sln
    - dotnet build ./EventFlowSample/EventFlowSample.sln
script:    
    - dotnet test ./EventFlowSample/GettingStartedTest/GettingStartedTest.csproj
