init:
  - git config --global core.autocrlf input

version: 1.0.{build}

image: Visual Studio 2019

artifacts:
  - path: Build\Packages\*nupkg

services:
  - postgresql101

nuget:
  account_feed: false
  project_feed: false
  disable_publish_on_pr: true
