init:
  - git config --global core.autocrlf input

version: 1.0.{build}

image: Visual Studio 2019

services: 
  - postgresql
  - rabbitmq

nuget:
  disable_publish_on_pr: true

before_build:
- cmd: >-
    cd ./EventFlowSample

    dotnet restore

build:
  publish_nuget: true
  include_nuget_references: true
  publish_aspnet_core: true
  publish_core_console: true
  parallel: true
  verbosity: minimal
